// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKivIhPRJ50Yb1OHLPInlBR0qXgVuPN-g',
    appId: '1:959511637289:web:387312e9df236c96ca5b38',
    messagingSenderId: '959511637289',
    projectId: 'applogin-d372c',
    authDomain: 'applogin-d372c.firebaseapp.com',
    storageBucket: 'applogin-d372c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjmDIcZ5a65hSzk2uawp5boRFx_hM29ko',
    appId: '1:959511637289:android:475ad05ed92879b8ca5b38',
    messagingSenderId: '959511637289',
    projectId: 'applogin-d372c',
    storageBucket: 'applogin-d372c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACWFU8ChVHgVLzxNGbbRPj8EtGCO_MuDE',
    appId: '1:959511637289:ios:ff26322733863c76ca5b38',
    messagingSenderId: '959511637289',
    projectId: 'applogin-d372c',
    storageBucket: 'applogin-d372c.appspot.com',
    iosClientId: '959511637289-hna0mh58k683ntfiml45ii8dnhf4ugqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACWFU8ChVHgVLzxNGbbRPj8EtGCO_MuDE',
    appId: '1:959511637289:ios:83cee9b4e796aeb9ca5b38',
    messagingSenderId: '959511637289',
    projectId: 'applogin-d372c',
    storageBucket: 'applogin-d372c.appspot.com',
    iosClientId: '959511637289-21pabamvbfrphc20rcuu99h3sn7jh98v.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
